### ISSUE TITLE
filltype & promotion?

### ISSUE THREAD

**Issue by timholy** [JuliaArrays/PaddedViews.jl#44]
```julia
julia> a = reshape(1:9, 3, 3)
3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

julia> PaddedView(0.0, a, (Base.OneTo(4), Base.OneTo(5)))
4×5 PaddedView(0, reshape(::UnitRange{Int64}, 3, 3), (Base.OneTo(4), Base.OneTo(5))) with eltype Int64:
 1  4  7  0  0
 2  5  8  0  0
 3  6  9  0  0
 0  0  0  0  0

julia> PaddedView(0.2, a, (Base.OneTo(4), Base.OneTo(5)))
ERROR: InexactError: Int64(0.2)
Stacktrace:
 [1] Int64
   @ ./float.jl:723 [inlined]
 [2] convert
   @ ./number.jl:7 [inlined]
 [3] PaddedView
   @ ~/.julia/dev/PaddedViews/src/PaddedViews.jl:102 [inlined]
 [4] PaddedView(fillvalue::Float64, data::Base.ReshapedArray{Int64, 2, UnitRange{Int64}, Tuple{}}, args::Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}})
   @ PaddedViews ~/.julia/dev/PaddedViews/src/PaddedViews.jl:96
 [5] top-level scope
   @ REPL[5]:1
```

Is this bad? It's fixable by promotion, do we want to change it?

The alternative, of course, is to simply agree to require the user to specify `PaddedView{T}` in such cases. We might consider registering an error hint?

**Comment by johnnychen94** [comment]
This is a case that `Int` type can't represent the meaning of `0.2`, so a promotion makes sense. Colorants(in ImageCore), Missing and Nothing are promoted in this case.

Unless the user changes the eltype of `a`, the performance issue still exists even if we declare `PaddedView{Float64}`. I think it's more reasonable to add a "performance caveat" section and document this?

**Comment by timholy** [comment]
It's a good point that we should defer to the array eltype unless the user explicitly requests it.
