### ISSUE TITLE
Dims Keyword addition

### ISSUE THREAD

**Issue by ashwanirathee** [JuliaArrays/PaddedViews.jl#48]
Hey @johnnychen94 ,I think this works but it looks clumsy.I would need some guidance:)question is where we apply dimension keyword effect which tells what to use and what not to.
Pluto Notebook: https://github.com/ashwani-rathee/Demos/blob/main/PaddedViewsIssue.jl
Pdf Version: https://github.com/ashwani-rathee/Demos/blob/main/%F0%9F%8E%88%20PaddedViewsIssue.pdf
```
function PaddedView(fillvalue::FT, data::AbstractArray{T}, args...) where {FT, T}
    PaddedView{filltype(FT, T)}(fillvalue, data, args...)
end

function PaddedView{FT}(fillvalue,data::AbstractArray{T,N},
			sz::Tuple{Integer,Vararg{Integer}},dims=1) where {FT,T,N}
	if(dims==0)
	  val=copy(sz[1])
	 new_tuple=(size(data)[2],val)
	elseif(dims==1)
	  val=copy(sz[2])
	 new_tuple=(val,size(data)[1])
	end			
        inds = map(OneTo, new_tuple)     
    PaddedView{FT,N,typeof(inds),typeof(data)}(convert(FT, fillvalue), data, inds)
end
```
Before applying dims like this in function,I applied it to the struct PaddedView too,but I am not sure which should we use..
I use it on this:
```
img_source = testimage("woman_darkhair")
pyramid = gaussian_pyramid(img_source, 5, 2, 1)
PaddedView(-1, pyramid[2], (512,512),0) # 0 if we want update in rows direction, and 1 if we want to update in columns direction
```
![](https://i.imgur.com/IMpn5FT.png)

**Comment by johnnychen94** [comment]
Would you mind opening a PR on this so that it's easier to review?

Although we're mostly dealing with 2D images, `PaddedView` is designed for general arrays so we need a better strategy to support arbitrary dimensions. (BTW we don't use `0` for the first dimension).

As a not-so-exact reference, you can find the "`new_tuple`" shape calculation implementation for `cat` in Base https://github.com/JuliaLang/julia/blob/faa3d41f239adeef2692b2ad312a81f93fce8710/base/abstractarray.jl#L1600-L1603, I'm not sure if it can be used directly but it worth a try.

I don't think there's any need to put `dims` support in `PaddedView` since there's only one array that we'll deal with, not speaking of the fact that `sz` already tells the `dims` information. The `dims` keyword is useful only when we have multiple array inputs, so I think where we actually need the `dims` keyword is `paddedviews` and `sym_paddedviews`.

BTW,  to keep consistency with `cat`s, I think `dims` should be a keyword argument instead of a positional argument.

**Comment by ashwanirathee** [comment]
I just realized most of the work is being done by mosaic function with _padded_cat https://github.com/JuliaArrays/MosaicViews.jl/blob/04a39e7e0a5ae1f1d97fa6a2e75aab334f053e0f/src/MosaicViews.jl#L392and mosaicview is called by mosaic later which had me confused on PaddedView part(https://github.com/JuliaArrays/MosaicViews.jl/blob/04a39e7e0a5ae1f1d97fa6a2e75aab334f053e0f/src/MosaicViews.jl#L300)
I wanted to update content of those types in sz,but they threw bunch of errors(since it's immutable),so just  kind of created a new_tuple to show a example :)

**Comment by johnnychen94** [comment]
Yeah, just adding the functionality in `_padded_cat` is also a doable way. But I do think we can do it on PaddedViews side and then directly use it in MosaicViews.

**Comment by ashwanirathee** [comment]
@johnnychen94 I had a doubt in this part ,that since inds passed are immutable  tuple with element of Base.OneTo{Int64} type and its passed same as fillvalue(as constants) in map(),we would need a function right to get the inds 
For example if  we want padding in only vertical direction and are able to find the max size amongs imgs with outerinds() function....still width is changing in each case of A or is there something I am missing about map....but if we run a function that returns indices in each case inside the map for all As,that would slow it down by quite a bit I think
``` 
--------This part ----------
function paddedviews(fillvalue, As::AbstractArray...)
    inds = outerinds(As...)   #This Part
    map(A->PaddedView(fillvalue, A, inds), As)
end
------------------------------
# Zero, one, and two arrays are common, improve inferrability
paddedviews(fillvalue) = ()
paddedviews(fillvalue, A1::AbstractArray) = (PaddedView(fillvalue, A1, outerinds(A1)),)
function paddedviews(fillvalue, A1::AbstractArray, A2::AbstractArray)
    inds = outerinds(A1, A2)
    PaddedView(fillvalue, A1, inds), PaddedView(fillvalue, A2, inds)
end

# This is an (unexported) optimization if you're supplying the arrays from a vector.
# MosaicViews uses this.
function paddedviews_itr(fillvalue, itr)
    inds = outerinds(itr...)
    [PaddedView(fillvalue, A, inds) for A in itr]
end

@inline outerinds(A::AbstractArray, Bs...) = _outerinds(axes(A), Bs...)
@inline _outerinds(inds, A::AbstractArray, Bs...) =
    _outerinds(__outerinds(inds, axes(A)), Bs...)
_outerinds(inds) = inds
@inline function __outerinds(inds1::NTuple{N,I}, inds2) where {N,I<:AbstractUnitRange}
    map((i1, i2) -> padrange(i1, i2), inds1, inds2)
end
```

**Comment by johnnychen94** [comment]
This is a very good question.

Unlike other languages that you may have used, You'll meet a lot of such kinds of recursive implementations using `Tuple`. Julia compiler (or LLVM) knows how to optimize Tuple (immutable and type stable) very well and gives very good runtime performance.

You can use [BenchmarkTool.jl](https://github.com/JuliaCI/BenchmarkTools.jl) to benchmark the performance if you're not aware of it yet.

```julia
julia> As = [rand(i, j) for (i,j) in zip(1:5, 2:6)];

julia> @btime PaddedViews.outerinds($As[1], $As[2], $As[3], $As[4], $As[5])
  5.183 ns (0 allocations: 0 bytes)
(Base.OneTo(5), Base.OneTo(6))

julia> @btime PaddedViews.outerinds($As...);
  592.067 ns (13 allocations: 416 bytes)
```

The first benchmark result shows the running time if `As` is a "constant" via variable interpolation. The second one is more interesting, it indicates some optimization room of this function by eliminating the memory allocation; I think it's mainly because `Array` is mutable. I don't know how to optimize this yet until I put my hands on it, probably via generated functions, I'm not sure of it.

---

For the feature in this issue, it seems that we need to modify this part and perhaps doing something like

```julia
function paddedviews(fillvalue, As::AbstractArray...)
    inds = outerinds(As...)   # this gives the "maximal" padding indices
    map(A->PaddedView(fillvalue, A, _extended_axes(A, inds, dims)), As, inds)
end

# replace `axes(A)` at given dimension `dims` using `inds[dims]`
_extended_axes(A, inds, ::Nothing) = inds
function _extended_axes(A, inds, dims::Int)
    map((r1, r2, d)->d?r2:r1, axes(A), inds, ntuple(i->i==dims, ndims(A)))
end
function _extended_axes(A, inds, dims::Tuple) # when dims is a tuple, e.g., dims=[1, 2]
    ....
end
```

Unsure if this works out of the box, but I hope you get the idea, could I leave it to you to put them together?

**Comment by ashwanirathee** [comment]
@johnnychen94 I had already made a indices function yesterday for new inds for each case but your code looks way more clean than what I made with simpler functions :) So I'll just put it all together today and make PRs for it,though even after we successfuly return images with different dimensions ,we get dimension mismatch error in cat function in mosaicviews.jl I think
```
##function that's currently returning indices
function indices(data::Tuple,inds::Tuple,dim::Int)
	# println(typeof(inds))
	new_tuple= (copy(inds[1]),copy(inds[1]))
	# println(new_tuple)
	# println(data)
	# println(sizeof(data))
	# inds = map(Int64, inds)
	# println(inds)
	# inds = map(Int64, inds)
	if(dim==1)
	  val=map(OneTo, data[2])
	  new_inds=(copy(inds[1]),val)
	  
			println(new_inds)
	  return new_inds
	elseif(dim==2)
	  val=map(OneTo,data[1])
	  new_inds=(val,copy(inds[2]))
	  println(new_inds)
	  return new_inds
	end
	# println(typeof(new_inds))
	return inds
end
function paddedviews(fillvalue,dim, As::AbstractArray...)
    inds = outerinds(As...)
    map(A->PaddedView(fillvalue, A, indices(size(A),inds,dim)), As)
end
```
```
My test console log
      From worker 2:	Test Pass 1 :inside mosaic
      From worker 2:	Inside Padded_ Cat1 :inside _padded_cat
      From worker 2:	Test Pass 2 :
      From worker 2:	hasoff :inside if statement of _padded_Cat
      From worker 2:	(Base.OneTo(512), Base.OneTo(512))
      From worker 2:	(Base.OneTo(512), Base.OneTo(256))
      From worker 2:	(Base.OneTo(512), Base.OneTo(128))
      From worker 2:	(Base.OneTo(512), Base.OneTo(64))
      From worker 2:	(Base.OneTo(512), Base.OneTo(32))

```

```
DimensionMismatch("mismatch in dimension 2 (expected 512 got 256)")

_cs@abstractarray.jl:1501[inlined]
_cshp@abstractarray.jl:1497[inlined]
_cshp@abstractarray.jl:1498[inlined]
cat_shape(::Tuple{Bool,Bool,Bool}, ::Tuple{Int64,Int64,Int64}, ::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}, ::Vararg{Tuple{Int64,Int64},N} where N)@abstractarray.jl:1476
_cat_t(::Val{3}, ::Type{T} where T, ::Main.workspace3.PaddedView{ColorTypes.Gray{Float64},2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},Array{ColorTypes.Gray{Float64},2}}, ::Vararg{Main.workspace3.PaddedView{ColorTypes.Gray{Float64},2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},Array{ColorTypes.Gray{Float64},2}},N} where N)@abstractarray.jl:1521
#_padded_cat#21(::Bool, ::Any, ::Any, ::Any, ::typeof(Main.workspace3._padded_cat), ::Any)@Other: 375
#mosaic#19(::ColorTypes.Gray{Float64}, ::Bool, ::Int64, ::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol,Symbol},NamedTuple{(:nrow, :ncol),Tuple{Int64,Int64}}}, ::typeof(Main.workspace3.mosaic), ::NTuple{5,Array{ColorTypes.Gray{Float64},2}})@Other: 332
#mosaic#17(::Base.Iterators.Pairs{Symbol,Integer,NTuple{4,Symbol},NamedTuple{(:nrow, :ncol, :center, :dim),Tuple{Int64,Int64,Bool,Int64}}}, ::typeof(Main.workspace3.mosaic), ::Array{ColorTypes.Gray{Float64},2}, ::Vararg{Array{ColorTypes.Gray{Float64},2},N} where N)@Other: 302
#mosaicview#26(::Base.Iterators.Pairs{Symbol,Integer,NTuple{4,Symbol},NamedTuple{(:nrow, :ncol, :center, :dim),Tuple{Int64,Int64,Bool,Int64}}}, ::typeof(Main.workspace3.mosaicview), ::Array{ColorTypes.Gray{Float64},2}, ::Vararg{Array{ColorTypes.Gray{Float64},2},N} where N)@deprecated.jl:72
top-level scope@Local: 4
```

**Comment by johnnychen94** [comment]
Please submit a PR when you're ready; it's easier to review the codes when it's formed in a PR form.
